// Code generated by ent, DO NOT EDIT.

package accesstokenkey

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the accesstokenkey type in the database.
	Label = "access_token_key"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPrivateKeyEncrypted holds the string denoting the private_key_encrypted field in the database.
	FieldPrivateKeyEncrypted = "private_key_encrypted"
	// FieldPublicPem holds the string denoting the public_pem field in the database.
	FieldPublicPem = "public_pem"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the accesstokenkey in the database.
	Table = "access_token_keys"
)

// Columns holds all SQL columns for accesstokenkey fields.
var Columns = []string{
	FieldID,
	FieldPrivateKeyEncrypted,
	FieldPublicPem,
	FieldState,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// PrivateKeyEncryptedValidator is a validator for the "private_key_encrypted" field. It is called by the builders before save.
	PrivateKeyEncryptedValidator func([]byte) error
	// PublicPemValidator is a validator for the "public_pem" field. It is called by the builders before save.
	PublicPemValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the AccessTokenKey queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPublicPem orders the results by the public_pem field.
func ByPublicPem(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicPem, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
