// Code generated by ent, DO NOT EDIT.

package accesstokenkey

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/teathedev/fullstack-boilerplate/backend/internal/ent/predicate"
	"github.com/teathedev/fullstack-boilerplate/backend/types"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldLTE(FieldID, id))
}

// PrivateKeyEncrypted applies equality check predicate on the "private_key_encrypted" field. It's identical to PrivateKeyEncryptedEQ.
func PrivateKeyEncrypted(v []byte) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldEQ(FieldPrivateKeyEncrypted, v))
}

// PublicPem applies equality check predicate on the "public_pem" field. It's identical to PublicPemEQ.
func PublicPem(v string) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldEQ(FieldPublicPem, v))
}

// State applies equality check predicate on the "state" field. It's identical to StateEQ.
func State(v types.AccessTokenKeyStates) predicate.AccessTokenKey {
	vc := int8(v)
	return predicate.AccessTokenKey(sql.FieldEQ(FieldState, vc))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldEQ(FieldUpdatedAt, v))
}

// PrivateKeyEncryptedEQ applies the EQ predicate on the "private_key_encrypted" field.
func PrivateKeyEncryptedEQ(v []byte) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldEQ(FieldPrivateKeyEncrypted, v))
}

// PrivateKeyEncryptedNEQ applies the NEQ predicate on the "private_key_encrypted" field.
func PrivateKeyEncryptedNEQ(v []byte) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldNEQ(FieldPrivateKeyEncrypted, v))
}

// PrivateKeyEncryptedIn applies the In predicate on the "private_key_encrypted" field.
func PrivateKeyEncryptedIn(vs ...[]byte) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldIn(FieldPrivateKeyEncrypted, vs...))
}

// PrivateKeyEncryptedNotIn applies the NotIn predicate on the "private_key_encrypted" field.
func PrivateKeyEncryptedNotIn(vs ...[]byte) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldNotIn(FieldPrivateKeyEncrypted, vs...))
}

// PrivateKeyEncryptedGT applies the GT predicate on the "private_key_encrypted" field.
func PrivateKeyEncryptedGT(v []byte) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldGT(FieldPrivateKeyEncrypted, v))
}

// PrivateKeyEncryptedGTE applies the GTE predicate on the "private_key_encrypted" field.
func PrivateKeyEncryptedGTE(v []byte) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldGTE(FieldPrivateKeyEncrypted, v))
}

// PrivateKeyEncryptedLT applies the LT predicate on the "private_key_encrypted" field.
func PrivateKeyEncryptedLT(v []byte) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldLT(FieldPrivateKeyEncrypted, v))
}

// PrivateKeyEncryptedLTE applies the LTE predicate on the "private_key_encrypted" field.
func PrivateKeyEncryptedLTE(v []byte) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldLTE(FieldPrivateKeyEncrypted, v))
}

// PublicPemEQ applies the EQ predicate on the "public_pem" field.
func PublicPemEQ(v string) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldEQ(FieldPublicPem, v))
}

// PublicPemNEQ applies the NEQ predicate on the "public_pem" field.
func PublicPemNEQ(v string) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldNEQ(FieldPublicPem, v))
}

// PublicPemIn applies the In predicate on the "public_pem" field.
func PublicPemIn(vs ...string) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldIn(FieldPublicPem, vs...))
}

// PublicPemNotIn applies the NotIn predicate on the "public_pem" field.
func PublicPemNotIn(vs ...string) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldNotIn(FieldPublicPem, vs...))
}

// PublicPemGT applies the GT predicate on the "public_pem" field.
func PublicPemGT(v string) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldGT(FieldPublicPem, v))
}

// PublicPemGTE applies the GTE predicate on the "public_pem" field.
func PublicPemGTE(v string) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldGTE(FieldPublicPem, v))
}

// PublicPemLT applies the LT predicate on the "public_pem" field.
func PublicPemLT(v string) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldLT(FieldPublicPem, v))
}

// PublicPemLTE applies the LTE predicate on the "public_pem" field.
func PublicPemLTE(v string) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldLTE(FieldPublicPem, v))
}

// PublicPemContains applies the Contains predicate on the "public_pem" field.
func PublicPemContains(v string) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldContains(FieldPublicPem, v))
}

// PublicPemHasPrefix applies the HasPrefix predicate on the "public_pem" field.
func PublicPemHasPrefix(v string) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldHasPrefix(FieldPublicPem, v))
}

// PublicPemHasSuffix applies the HasSuffix predicate on the "public_pem" field.
func PublicPemHasSuffix(v string) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldHasSuffix(FieldPublicPem, v))
}

// PublicPemEqualFold applies the EqualFold predicate on the "public_pem" field.
func PublicPemEqualFold(v string) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldEqualFold(FieldPublicPem, v))
}

// PublicPemContainsFold applies the ContainsFold predicate on the "public_pem" field.
func PublicPemContainsFold(v string) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldContainsFold(FieldPublicPem, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v types.AccessTokenKeyStates) predicate.AccessTokenKey {
	vc := int8(v)
	return predicate.AccessTokenKey(sql.FieldEQ(FieldState, vc))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v types.AccessTokenKeyStates) predicate.AccessTokenKey {
	vc := int8(v)
	return predicate.AccessTokenKey(sql.FieldNEQ(FieldState, vc))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...types.AccessTokenKeyStates) predicate.AccessTokenKey {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int8(vs[i])
	}
	return predicate.AccessTokenKey(sql.FieldIn(FieldState, v...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...types.AccessTokenKeyStates) predicate.AccessTokenKey {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int8(vs[i])
	}
	return predicate.AccessTokenKey(sql.FieldNotIn(FieldState, v...))
}

// StateGT applies the GT predicate on the "state" field.
func StateGT(v types.AccessTokenKeyStates) predicate.AccessTokenKey {
	vc := int8(v)
	return predicate.AccessTokenKey(sql.FieldGT(FieldState, vc))
}

// StateGTE applies the GTE predicate on the "state" field.
func StateGTE(v types.AccessTokenKeyStates) predicate.AccessTokenKey {
	vc := int8(v)
	return predicate.AccessTokenKey(sql.FieldGTE(FieldState, vc))
}

// StateLT applies the LT predicate on the "state" field.
func StateLT(v types.AccessTokenKeyStates) predicate.AccessTokenKey {
	vc := int8(v)
	return predicate.AccessTokenKey(sql.FieldLT(FieldState, vc))
}

// StateLTE applies the LTE predicate on the "state" field.
func StateLTE(v types.AccessTokenKeyStates) predicate.AccessTokenKey {
	vc := int8(v)
	return predicate.AccessTokenKey(sql.FieldLTE(FieldState, vc))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AccessTokenKey) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AccessTokenKey) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AccessTokenKey) predicate.AccessTokenKey {
	return predicate.AccessTokenKey(sql.NotPredicates(p))
}
