// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/teathedev/fullstack-boilerplate/backend/internal/ent/accesstokenkey"
	"github.com/teathedev/fullstack-boilerplate/backend/internal/ent/predicate"
	"github.com/teathedev/fullstack-boilerplate/backend/types"
)

// AccessTokenKeyUpdate is the builder for updating AccessTokenKey entities.
type AccessTokenKeyUpdate struct {
	config
	hooks    []Hook
	mutation *AccessTokenKeyMutation
}

// Where appends a list predicates to the AccessTokenKeyUpdate builder.
func (_u *AccessTokenKeyUpdate) Where(ps ...predicate.AccessTokenKey) *AccessTokenKeyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPrivateKeyEncrypted sets the "private_key_encrypted" field.
func (_u *AccessTokenKeyUpdate) SetPrivateKeyEncrypted(v []byte) *AccessTokenKeyUpdate {
	_u.mutation.SetPrivateKeyEncrypted(v)
	return _u
}

// SetPublicPem sets the "public_pem" field.
func (_u *AccessTokenKeyUpdate) SetPublicPem(v string) *AccessTokenKeyUpdate {
	_u.mutation.SetPublicPem(v)
	return _u
}

// SetNillablePublicPem sets the "public_pem" field if the given value is not nil.
func (_u *AccessTokenKeyUpdate) SetNillablePublicPem(v *string) *AccessTokenKeyUpdate {
	if v != nil {
		_u.SetPublicPem(*v)
	}
	return _u
}

// SetState sets the "state" field.
func (_u *AccessTokenKeyUpdate) SetState(v types.AccessTokenKeyStates) *AccessTokenKeyUpdate {
	_u.mutation.ResetState()
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *AccessTokenKeyUpdate) SetNillableState(v *types.AccessTokenKeyStates) *AccessTokenKeyUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// AddState adds value to the "state" field.
func (_u *AccessTokenKeyUpdate) AddState(v types.AccessTokenKeyStates) *AccessTokenKeyUpdate {
	_u.mutation.AddState(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccessTokenKeyUpdate) SetUpdatedAt(v time.Time) *AccessTokenKeyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AccessTokenKeyMutation object of the builder.
func (_u *AccessTokenKeyUpdate) Mutation() *AccessTokenKeyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccessTokenKeyUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccessTokenKeyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccessTokenKeyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccessTokenKeyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccessTokenKeyUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accesstokenkey.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccessTokenKeyUpdate) check() error {
	if v, ok := _u.mutation.PrivateKeyEncrypted(); ok {
		if err := accesstokenkey.PrivateKeyEncryptedValidator(v); err != nil {
			return &ValidationError{Name: "private_key_encrypted", err: fmt.Errorf(`ent: validator failed for field "AccessTokenKey.private_key_encrypted": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PublicPem(); ok {
		if err := accesstokenkey.PublicPemValidator(v); err != nil {
			return &ValidationError{Name: "public_pem", err: fmt.Errorf(`ent: validator failed for field "AccessTokenKey.public_pem": %w`, err)}
		}
	}
	return nil
}

func (_u *AccessTokenKeyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accesstokenkey.Table, accesstokenkey.Columns, sqlgraph.NewFieldSpec(accesstokenkey.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PrivateKeyEncrypted(); ok {
		_spec.SetField(accesstokenkey.FieldPrivateKeyEncrypted, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.PublicPem(); ok {
		_spec.SetField(accesstokenkey.FieldPublicPem, field.TypeString, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(accesstokenkey.FieldState, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedState(); ok {
		_spec.AddField(accesstokenkey.FieldState, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accesstokenkey.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accesstokenkey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccessTokenKeyUpdateOne is the builder for updating a single AccessTokenKey entity.
type AccessTokenKeyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccessTokenKeyMutation
}

// SetPrivateKeyEncrypted sets the "private_key_encrypted" field.
func (_u *AccessTokenKeyUpdateOne) SetPrivateKeyEncrypted(v []byte) *AccessTokenKeyUpdateOne {
	_u.mutation.SetPrivateKeyEncrypted(v)
	return _u
}

// SetPublicPem sets the "public_pem" field.
func (_u *AccessTokenKeyUpdateOne) SetPublicPem(v string) *AccessTokenKeyUpdateOne {
	_u.mutation.SetPublicPem(v)
	return _u
}

// SetNillablePublicPem sets the "public_pem" field if the given value is not nil.
func (_u *AccessTokenKeyUpdateOne) SetNillablePublicPem(v *string) *AccessTokenKeyUpdateOne {
	if v != nil {
		_u.SetPublicPem(*v)
	}
	return _u
}

// SetState sets the "state" field.
func (_u *AccessTokenKeyUpdateOne) SetState(v types.AccessTokenKeyStates) *AccessTokenKeyUpdateOne {
	_u.mutation.ResetState()
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *AccessTokenKeyUpdateOne) SetNillableState(v *types.AccessTokenKeyStates) *AccessTokenKeyUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// AddState adds value to the "state" field.
func (_u *AccessTokenKeyUpdateOne) AddState(v types.AccessTokenKeyStates) *AccessTokenKeyUpdateOne {
	_u.mutation.AddState(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccessTokenKeyUpdateOne) SetUpdatedAt(v time.Time) *AccessTokenKeyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AccessTokenKeyMutation object of the builder.
func (_u *AccessTokenKeyUpdateOne) Mutation() *AccessTokenKeyMutation {
	return _u.mutation
}

// Where appends a list predicates to the AccessTokenKeyUpdate builder.
func (_u *AccessTokenKeyUpdateOne) Where(ps ...predicate.AccessTokenKey) *AccessTokenKeyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccessTokenKeyUpdateOne) Select(field string, fields ...string) *AccessTokenKeyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AccessTokenKey entity.
func (_u *AccessTokenKeyUpdateOne) Save(ctx context.Context) (*AccessTokenKey, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccessTokenKeyUpdateOne) SaveX(ctx context.Context) *AccessTokenKey {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccessTokenKeyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccessTokenKeyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccessTokenKeyUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accesstokenkey.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccessTokenKeyUpdateOne) check() error {
	if v, ok := _u.mutation.PrivateKeyEncrypted(); ok {
		if err := accesstokenkey.PrivateKeyEncryptedValidator(v); err != nil {
			return &ValidationError{Name: "private_key_encrypted", err: fmt.Errorf(`ent: validator failed for field "AccessTokenKey.private_key_encrypted": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PublicPem(); ok {
		if err := accesstokenkey.PublicPemValidator(v); err != nil {
			return &ValidationError{Name: "public_pem", err: fmt.Errorf(`ent: validator failed for field "AccessTokenKey.public_pem": %w`, err)}
		}
	}
	return nil
}

func (_u *AccessTokenKeyUpdateOne) sqlSave(ctx context.Context) (_node *AccessTokenKey, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accesstokenkey.Table, accesstokenkey.Columns, sqlgraph.NewFieldSpec(accesstokenkey.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AccessTokenKey.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accesstokenkey.FieldID)
		for _, f := range fields {
			if !accesstokenkey.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accesstokenkey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PrivateKeyEncrypted(); ok {
		_spec.SetField(accesstokenkey.FieldPrivateKeyEncrypted, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.PublicPem(); ok {
		_spec.SetField(accesstokenkey.FieldPublicPem, field.TypeString, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(accesstokenkey.FieldState, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedState(); ok {
		_spec.AddField(accesstokenkey.FieldState, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accesstokenkey.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &AccessTokenKey{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accesstokenkey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
