// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/teathedev/backend-boilerplate/internal/ent/accesstokenkey"
	"github.com/teathedev/backend-boilerplate/types"
)

// AccessTokenKey is the model entity for the AccessTokenKey schema.
type AccessTokenKey struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// PrivateKeyEncrypted holds the value of the "private_key_encrypted" field.
	PrivateKeyEncrypted []byte `json:"private_key_encrypted,omitempty"`
	// PublicPem holds the value of the "public_pem" field.
	PublicPem string `json:"public_pem,omitempty"`
	// State holds the value of the "state" field.
	State types.AccessTokenKeyStates `json:"state,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccessTokenKey) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accesstokenkey.FieldPrivateKeyEncrypted:
			values[i] = new([]byte)
		case accesstokenkey.FieldState:
			values[i] = new(sql.NullInt64)
		case accesstokenkey.FieldPublicPem:
			values[i] = new(sql.NullString)
		case accesstokenkey.FieldCreatedAt, accesstokenkey.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case accesstokenkey.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccessTokenKey fields.
func (_m *AccessTokenKey) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accesstokenkey.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case accesstokenkey.FieldPrivateKeyEncrypted:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field private_key_encrypted", values[i])
			} else if value != nil {
				_m.PrivateKeyEncrypted = *value
			}
		case accesstokenkey.FieldPublicPem:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field public_pem", values[i])
			} else if value.Valid {
				_m.PublicPem = value.String
			}
		case accesstokenkey.FieldState:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = types.AccessTokenKeyStates(value.Int64)
			}
		case accesstokenkey.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case accesstokenkey.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccessTokenKey.
// This includes values selected through modifiers, order, etc.
func (_m *AccessTokenKey) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AccessTokenKey.
// Note that you need to call AccessTokenKey.Unwrap() before calling this method if this AccessTokenKey
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AccessTokenKey) Update() *AccessTokenKeyUpdateOne {
	return NewAccessTokenKeyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AccessTokenKey entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AccessTokenKey) Unwrap() *AccessTokenKey {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccessTokenKey is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AccessTokenKey) String() string {
	var builder strings.Builder
	builder.WriteString("AccessTokenKey(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("private_key_encrypted=")
	builder.WriteString(fmt.Sprintf("%v", _m.PrivateKeyEncrypted))
	builder.WriteString(", ")
	builder.WriteString("public_pem=")
	builder.WriteString(_m.PublicPem)
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(fmt.Sprintf("%v", _m.State))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AccessTokenKeys is a parsable slice of AccessTokenKey.
type AccessTokenKeys []*AccessTokenKey
