// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/teathedev/backend-boilerplate/internal/ent/accesstokenkey"
	"github.com/teathedev/backend-boilerplate/types"
)

// AccessTokenKeyCreate is the builder for creating a AccessTokenKey entity.
type AccessTokenKeyCreate struct {
	config
	mutation *AccessTokenKeyMutation
	hooks    []Hook
}

// SetPrivateKeyEncrypted sets the "private_key_encrypted" field.
func (_c *AccessTokenKeyCreate) SetPrivateKeyEncrypted(v []byte) *AccessTokenKeyCreate {
	_c.mutation.SetPrivateKeyEncrypted(v)
	return _c
}

// SetPublicPem sets the "public_pem" field.
func (_c *AccessTokenKeyCreate) SetPublicPem(v string) *AccessTokenKeyCreate {
	_c.mutation.SetPublicPem(v)
	return _c
}

// SetState sets the "state" field.
func (_c *AccessTokenKeyCreate) SetState(v types.AccessTokenKeyStates) *AccessTokenKeyCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccessTokenKeyCreate) SetCreatedAt(v time.Time) *AccessTokenKeyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccessTokenKeyCreate) SetNillableCreatedAt(v *time.Time) *AccessTokenKeyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AccessTokenKeyCreate) SetUpdatedAt(v time.Time) *AccessTokenKeyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AccessTokenKeyCreate) SetNillableUpdatedAt(v *time.Time) *AccessTokenKeyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AccessTokenKeyCreate) SetID(v uuid.UUID) *AccessTokenKeyCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AccessTokenKeyCreate) SetNillableID(v *uuid.UUID) *AccessTokenKeyCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the AccessTokenKeyMutation object of the builder.
func (_c *AccessTokenKeyCreate) Mutation() *AccessTokenKeyMutation {
	return _c.mutation
}

// Save creates the AccessTokenKey in the database.
func (_c *AccessTokenKeyCreate) Save(ctx context.Context) (*AccessTokenKey, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccessTokenKeyCreate) SaveX(ctx context.Context) *AccessTokenKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccessTokenKeyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccessTokenKeyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccessTokenKeyCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := accesstokenkey.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := accesstokenkey.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := accesstokenkey.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccessTokenKeyCreate) check() error {
	if _, ok := _c.mutation.PrivateKeyEncrypted(); !ok {
		return &ValidationError{Name: "private_key_encrypted", err: errors.New(`ent: missing required field "AccessTokenKey.private_key_encrypted"`)}
	}
	if v, ok := _c.mutation.PrivateKeyEncrypted(); ok {
		if err := accesstokenkey.PrivateKeyEncryptedValidator(v); err != nil {
			return &ValidationError{Name: "private_key_encrypted", err: fmt.Errorf(`ent: validator failed for field "AccessTokenKey.private_key_encrypted": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PublicPem(); !ok {
		return &ValidationError{Name: "public_pem", err: errors.New(`ent: missing required field "AccessTokenKey.public_pem"`)}
	}
	if v, ok := _c.mutation.PublicPem(); ok {
		if err := accesstokenkey.PublicPemValidator(v); err != nil {
			return &ValidationError{Name: "public_pem", err: fmt.Errorf(`ent: validator failed for field "AccessTokenKey.public_pem": %w`, err)}
		}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "AccessTokenKey.state"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AccessTokenKey.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AccessTokenKey.updated_at"`)}
	}
	return nil
}

func (_c *AccessTokenKeyCreate) sqlSave(ctx context.Context) (*AccessTokenKey, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccessTokenKeyCreate) createSpec() (*AccessTokenKey, *sqlgraph.CreateSpec) {
	var (
		_node = &AccessTokenKey{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accesstokenkey.Table, sqlgraph.NewFieldSpec(accesstokenkey.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.PrivateKeyEncrypted(); ok {
		_spec.SetField(accesstokenkey.FieldPrivateKeyEncrypted, field.TypeBytes, value)
		_node.PrivateKeyEncrypted = value
	}
	if value, ok := _c.mutation.PublicPem(); ok {
		_spec.SetField(accesstokenkey.FieldPublicPem, field.TypeString, value)
		_node.PublicPem = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(accesstokenkey.FieldState, field.TypeInt8, value)
		_node.State = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(accesstokenkey.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(accesstokenkey.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// AccessTokenKeyCreateBulk is the builder for creating many AccessTokenKey entities in bulk.
type AccessTokenKeyCreateBulk struct {
	config
	err      error
	builders []*AccessTokenKeyCreate
}

// Save creates the AccessTokenKey entities in the database.
func (_c *AccessTokenKeyCreateBulk) Save(ctx context.Context) ([]*AccessTokenKey, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccessTokenKey, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccessTokenKeyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccessTokenKeyCreateBulk) SaveX(ctx context.Context) []*AccessTokenKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccessTokenKeyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccessTokenKeyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
