// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/teathedev/fullstack-boilerplate/backend/internal/ent/accesstokenkey"
	"github.com/teathedev/fullstack-boilerplate/backend/internal/ent/predicate"
)

// AccessTokenKeyDelete is the builder for deleting a AccessTokenKey entity.
type AccessTokenKeyDelete struct {
	config
	hooks    []Hook
	mutation *AccessTokenKeyMutation
}

// Where appends a list predicates to the AccessTokenKeyDelete builder.
func (_d *AccessTokenKeyDelete) Where(ps ...predicate.AccessTokenKey) *AccessTokenKeyDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AccessTokenKeyDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccessTokenKeyDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AccessTokenKeyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(accesstokenkey.Table, sqlgraph.NewFieldSpec(accesstokenkey.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AccessTokenKeyDeleteOne is the builder for deleting a single AccessTokenKey entity.
type AccessTokenKeyDeleteOne struct {
	_d *AccessTokenKeyDelete
}

// Where appends a list predicates to the AccessTokenKeyDelete builder.
func (_d *AccessTokenKeyDeleteOne) Where(ps ...predicate.AccessTokenKey) *AccessTokenKeyDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AccessTokenKeyDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{accesstokenkey.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccessTokenKeyDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
