// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/teathedev/fullstack-boilerplate/backend/internal/ent/accesstokenkey"
	"github.com/teathedev/fullstack-boilerplate/backend/internal/ent/refreshtoken"
	"github.com/teathedev/fullstack-boilerplate/backend/internal/ent/schema"
	"github.com/teathedev/fullstack-boilerplate/backend/internal/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accesstokenkeyFields := schema.AccessTokenKey{}.Fields()
	_ = accesstokenkeyFields
	// accesstokenkeyDescPrivateKeyEncrypted is the schema descriptor for private_key_encrypted field.
	accesstokenkeyDescPrivateKeyEncrypted := accesstokenkeyFields[1].Descriptor()
	// accesstokenkey.PrivateKeyEncryptedValidator is a validator for the "private_key_encrypted" field. It is called by the builders before save.
	accesstokenkey.PrivateKeyEncryptedValidator = accesstokenkeyDescPrivateKeyEncrypted.Validators[0].(func([]byte) error)
	// accesstokenkeyDescPublicPem is the schema descriptor for public_pem field.
	accesstokenkeyDescPublicPem := accesstokenkeyFields[2].Descriptor()
	// accesstokenkey.PublicPemValidator is a validator for the "public_pem" field. It is called by the builders before save.
	accesstokenkey.PublicPemValidator = accesstokenkeyDescPublicPem.Validators[0].(func(string) error)
	// accesstokenkeyDescCreatedAt is the schema descriptor for created_at field.
	accesstokenkeyDescCreatedAt := accesstokenkeyFields[4].Descriptor()
	// accesstokenkey.DefaultCreatedAt holds the default value on creation for the created_at field.
	accesstokenkey.DefaultCreatedAt = accesstokenkeyDescCreatedAt.Default.(func() time.Time)
	// accesstokenkeyDescUpdatedAt is the schema descriptor for updated_at field.
	accesstokenkeyDescUpdatedAt := accesstokenkeyFields[5].Descriptor()
	// accesstokenkey.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	accesstokenkey.DefaultUpdatedAt = accesstokenkeyDescUpdatedAt.Default.(func() time.Time)
	// accesstokenkey.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	accesstokenkey.UpdateDefaultUpdatedAt = accesstokenkeyDescUpdatedAt.UpdateDefault.(func() time.Time)
	// accesstokenkeyDescID is the schema descriptor for id field.
	accesstokenkeyDescID := accesstokenkeyFields[0].Descriptor()
	// accesstokenkey.DefaultID holds the default value on creation for the id field.
	accesstokenkey.DefaultID = accesstokenkeyDescID.Default.(func() uuid.UUID)
	refreshtokenFields := schema.RefreshToken{}.Fields()
	_ = refreshtokenFields
	// refreshtokenDescIsClaimed is the schema descriptor for is_claimed field.
	refreshtokenDescIsClaimed := refreshtokenFields[2].Descriptor()
	// refreshtoken.DefaultIsClaimed holds the default value on creation for the is_claimed field.
	refreshtoken.DefaultIsClaimed = refreshtokenDescIsClaimed.Default.(bool)
	// refreshtokenDescToken is the schema descriptor for token field.
	refreshtokenDescToken := refreshtokenFields[3].Descriptor()
	// refreshtoken.TokenValidator is a validator for the "token" field. It is called by the builders before save.
	refreshtoken.TokenValidator = func() func(string) error {
		validators := refreshtokenDescToken.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(token string) error {
			for _, fn := range fns {
				if err := fn(token); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// refreshtokenDescCreatedAt is the schema descriptor for created_at field.
	refreshtokenDescCreatedAt := refreshtokenFields[4].Descriptor()
	// refreshtoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	refreshtoken.DefaultCreatedAt = refreshtokenDescCreatedAt.Default.(func() time.Time)
	// refreshtokenDescUpdatedAt is the schema descriptor for updated_at field.
	refreshtokenDescUpdatedAt := refreshtokenFields[5].Descriptor()
	// refreshtoken.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	refreshtoken.DefaultUpdatedAt = refreshtokenDescUpdatedAt.Default.(func() time.Time)
	// refreshtoken.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	refreshtoken.UpdateDefaultUpdatedAt = refreshtokenDescUpdatedAt.UpdateDefault.(func() time.Time)
	// refreshtokenDescID is the schema descriptor for id field.
	refreshtokenDescID := refreshtokenFields[0].Descriptor()
	// refreshtoken.DefaultID holds the default value on creation for the id field.
	refreshtoken.DefaultID = refreshtokenDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescPhoneNumber is the schema descriptor for phone_number field.
	userDescPhoneNumber := userFields[1].Descriptor()
	// user.PhoneNumberValidator is a validator for the "phone_number" field. It is called by the builders before save.
	user.PhoneNumberValidator = func() func(string) error {
		validators := userDescPhoneNumber.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(phone_number string) error {
			for _, fn := range fns {
				if err := fn(phone_number); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[2].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = func() func(string) error {
		validators := userDescEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(email string) error {
			for _, fn := range fns {
				if err := fn(email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[3].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = func() func(string) error {
		validators := userDescUsername.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(username string) error {
			for _, fn := range fns {
				if err := fn(username); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescFirstName is the schema descriptor for first_name field.
	userDescFirstName := userFields[6].Descriptor()
	// user.FirstNameValidator is a validator for the "first_name" field. It is called by the builders before save.
	user.FirstNameValidator = func() func(string) error {
		validators := userDescFirstName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(first_name string) error {
			for _, fn := range fns {
				if err := fn(first_name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescLastName is the schema descriptor for last_name field.
	userDescLastName := userFields[7].Descriptor()
	// user.LastNameValidator is a validator for the "last_name" field. It is called by the builders before save.
	user.LastNameValidator = func() func(string) error {
		validators := userDescLastName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(last_name string) error {
			for _, fn := range fns {
				if err := fn(last_name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescPasswordSalt is the schema descriptor for password_salt field.
	userDescPasswordSalt := userFields[8].Descriptor()
	// user.PasswordSaltValidator is a validator for the "password_salt" field. It is called by the builders before save.
	user.PasswordSaltValidator = func() func(string) error {
		validators := userDescPasswordSalt.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(password_salt string) error {
			for _, fn := range fns {
				if err := fn(password_salt); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[9].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = func() func(string) error {
		validators := userDescPasswordHash.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(password_hash string) error {
			for _, fn := range fns {
				if err := fn(password_hash); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[10].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[11].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
